### ISSUE TITLE
Remove the drop shadow from the floating action buttons 

### ISSUE THREAD

**Issue by ChristianGrieger** [Galilel-Project/galilel-android#19]
Please remove the box shadow from all floating action buttons.

![Screenshot_2019-08-21-08-26-24](https://user-images.githubusercontent.com/8712219/63414074-5c0bde00-c3fb-11e9-93f6-4494d87c1ea8.png)

**Comment by mbroemme** [comment]
@ChristianGrieger what is the reason behind it. Why they should be removed?

**Comment by ChristianGrieger** [comment]
@mbroemme Because the complete app does not use shadows. In addition, there is no shadow on the project website and none in any of the documents created by the team. It will definitely look cleaner.

**Comment by mbroemme** [comment]
Fixed with PR #27
