### ISSUE TITLE
Wrong position for the icon on the value field for send and recieve tab

### ISSUE THREAD

**Issue by ChristianGrieger** [Galilel-Project/galilel-android#20]
The icon that makes it possible to switch between the selected currency and Gali has a wrong position on the input field.

![Screenshot_2019-08-21-08-26-01](https://user-images.githubusercontent.com/8712219/63414191-9c6b5c00-c3fb-11e9-8c8d-f833b85e2bc7.png)

**Comment by mbroemme** [comment]
@ChristianGrieger could you please add information about used Android version and which mobile phone. On the tested Pixel 2 with Android 9 it is properly aligned. Need to check it on your version.

**Comment by ChristianGrieger** [comment]
Huawai P9, Android Version 6, EMUI-Version 4.1, Model EVA-L09, Screen 1080x1920

**Comment by mbroemme** [comment]
Fixed with PR #27
