### ISSUE TITLE
Top right menu "Clean" is not needed

### ISSUE THREAD

**Issue by ChristianGrieger** [Galilel-Project/galilel-android#21]
The clean option on nearly all tabs of the app is not needed as users can use the back arrow. Else change the name "Clean" to "Back"
![Screenshot_2019-08-21-08-25-07](https://user-images.githubusercontent.com/8712219/63414470-359a7280-c3fc-11e9-989f-988463c12542.png)

**Comment by mbroemme** [comment]
@ChristianGrieger Clean is clearing the input fields if you entered something and want to restart, while back is going back to previous screen?

**Comment by ChristianGrieger** [comment]
@mbroemme When i am on the multi send page and enter something and click the clean it switch back to the prev apge and does not clean the inputs.

**Comment by mbroemme** [comment]
Fixed with PR #27
