### ISSUE TITLE
Change texts for Multilingual Support

### ISSUE THREAD

**Issue by cryptogerman** [Galilel-Project/galilel-android#8]
![PhotoEditor_20190605_115907546](https://user-images.githubusercontent.com/46231680/58950128-556fb200-878e-11e9-9b54-94da2c4859d6.jpg)
![PhotoEditor_20190605_101456080](https://user-images.githubusercontent.com/46231680/58950130-56084880-878e-11e9-8727-49bdb92eff1b.jpg)
![PhotoEditor_20190605_101703625](https://user-images.githubusercontent.com/46231680/58950131-56084880-878e-11e9-927e-09e072a6c77d.jpg)
![PhotoEditor_20190605_101747771](https://user-images.githubusercontent.com/46231680/58950132-56084880-878e-11e9-9cb4-fa46d2b65bdd.jpg)
![PhotoEditor_20190605_101825775](https://user-images.githubusercontent.com/46231680/58950133-56084880-878e-11e9-892f-f1f083fcd803.jpg)
![PhotoEditor_20190605_101850260](https://user-images.githubusercontent.com/46231680/58950134-56a0df00-878e-11e9-8a17-c86a17eb8009.jpg)
![PhotoEditor_20190605_101948887](https://user-images.githubusercontent.com/46231680/58950135-56a0df00-878e-11e9-9dec-2f2bca7a4dbd.jpg)
![PhotoEditor_20190605_102108986](https://user-images.githubusercontent.com/46231680/58950137-56a0df00-878e-11e9-9d4b-6845adf91440.jpg)
![PhotoEditor_20190605_102136176](https://user-images.githubusercontent.com/46231680/58950138-56a0df00-878e-11e9-84ef-61cb30438cd5.jpg)
![PhotoEditor_20190605_115109258](https://user-images.githubusercontent.com/46231680/58950139-57397580-878e-11e9-8900-bd04b2000066.jpg)
![PhotoEditor_20190605_115207588](https://user-images.githubusercontent.com/46231680/58950140-57397580-878e-11e9-9500-a1c923d557e5.jpg)
![PhotoEditor_20190605_115443890](https://user-images.githubusercontent.com/46231680/58950141-57397580-878e-11e9-849a-103360a2855a.jpg)
![PhotoEditor_20190605_115732370](https://user-images.githubusercontent.com/46231680/58950142-57d20c00-878e-11e9-8213-4b77fd997768.jpg)
![PhotoEditor_20190605_115807052](https://user-images.githubusercontent.com/46231680/58950144-57d20c00-878e-11e9-9dc0-3d4d280c9245.jpg)
![PhotoEditor_20190605_115831247](https://user-images.githubusercontent.com/46231680/58950145-57d20c00-878e-11e9-895f-7cf233711005.jpg)

**Comment by mbroemme** [comment]
Fixed by PR #13
